version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - HOST=0.0.0.0

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT=5000
